### ISSUE TITLE
Absent speaker embedding in speaker_embed.py

### ISSUE THREAD

**Issue by wxing232** [SolomidHero/speech-regeneration-enhancer#2]
Hello：
in speaker_embed.py， used 'hbredin/SpeakerEmbedding-XVectorMFCC-VoxCeleb' ,but 'hbredin/SpeakerEmbedding-XVectorMFCC-VoxCeleb' have been deleted. https://huggingface.co/hbredin/ . So what should i do .
thank you for your reply

**Comment by SolomidHero** [comment]
Hi, that's why tests weren't passed a while :)
Either you can to solve this by:
1. find how to load other model from https://github.com/pyannote/pyannote-audio/ which is used here
2. or use another package for speaker embedding extraction. There are plenty of models which were trained on speaker classification task. For example, you can use pre-trained model from https://github.com/resemble-ai/Resemblyzer/ as it is easy to use

**Comment by wxing232** [comment]
OK，thank you so much
